### ISSUE TITLE
Sripada and Personal information pages

### ISSUE THREAD

**Issue by HarindaVithana** [moe-lk/ncoe#174]
- [x] Put a notice on the Sripada NCOE page.
- [x] Recendent ---> spelling mistakes. Better changing to Permanent Residence District Name and Number
- [x] ...according to the section ---> ...according to section
- [x] Ethnicity must be changed to Race.

**Comment by dulanjanabandara** [comment]
Only the field name Ethnicity changed to Race. Any other internal structure did not change considering the site's internal behavior.
